# Must be unique in a given SonarQube instance
sonar.projectKey=next-redux-template

# This is the name and version displayed in the SonarQube UI.
# Was mandatory prior to SonarQube 6.1.
sonar.projectName=Next Redux Template
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
# Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=src, *.ts, *.json, *.md,

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**, **/dist/**, src/assets/**/*.js, **/.next/**