import type { Metadata } from "next";
import "../tailwind.css";
import "../globals.scss";
import { clsx } from "clsx";
import { SUPPORTED_LANGUAGES } from "@/i18n";
import ClientThemeProvider from "@/lib/ClientThemeProvider";
import { fontVariables } from "@/lib/fonts";
import LanguageProvider from "@/lib/LanguageProvider";
import { StoreProvider } from "@/lib/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Force static generation for this segment and disable ISR
export const dynamic = "force-static";
export const revalidate = false;

// Pre-render all supported locales at build time
export function generateStaticParams() {
  return SUPPORTED_LANGUAGES.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html
      lang={locale}
      className={clsx(fontVariables)}
      suppressHydrationWarning
    >
      <head>
        {/* Blocking script: sets data-theme before first paint to prevent flickering */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var v=['system','light','dark'];document.documentElement.setAttribute('data-theme',v.includes(t)?t:'system')}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <ClientThemeProvider>
            <LanguageProvider locale={locale}>{children}</LanguageProvider>
          </ClientThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
